In [1]:
import numpy as np

In [3]:
a = np.arange(15).reshape(3, 5)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [4]:
a.shape

(3, 5)

In [5]:
a.ndim

2

In [6]:
a.dtype.name

'int64'

In [7]:
a.itemsize

8

In [9]:
a.size

15

In [10]:
type(a)

numpy.ndarray

In [11]:
b = np.array([6, 7, 8])

In [12]:
b

array([6, 7, 8])

In [13]:
type(b)

numpy.ndarray

In [14]:
b

array([6, 7, 8])

In [16]:
c = np.array([[1,2], [3,4]], dtype=complex)

In [17]:
c

array([[ 1.+0.j,  2.+0.j],
       [ 3.+0.j,  4.+0.j]])

In [18]:
np.zeros((3,4))

array([[ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.]])

In [19]:
np.ones((2, 3, 4), dtype=np.int16)

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]], dtype=int16)

In [20]:
a = np.ones((2, 3), dtype=int)

In [21]:
a

array([[1, 1, 1],
       [1, 1, 1]])

In [22]:
b = np.random.random((2,3))

In [23]:
b

array([[ 0.92536929,  0.64215458,  0.6861546 ],
       [ 0.08282299,  0.04640128,  0.38209142]])

In [24]:
a *= 3

In [25]:
a

array([[3, 3, 3],
       [3, 3, 3]])

In [26]:
b += a

In [27]:
b

array([[ 3.92536929,  3.64215458,  3.6861546 ],
       [ 3.08282299,  3.04640128,  3.38209142]])

In [28]:
a += b

TypeError: Cannot cast ufunc add output from dtype('float64') to dtype('int64') with casting rule 'same_kind'

In [30]:
from numpy import pi
np.linspace(0, pi, 3)

array([ 0.        ,  1.57079633,  3.14159265])

In [38]:
b = np.arange(12).reshape(3, 4)
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [37]:
b.sum(axis=1)

array([ 6, 22, 38])